development:
  adapter: postgresql
  encoding: unicode
  database: redwings_development
  pool: 5
  username: [insert your user name]
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: redwings_test
  pool: 5
  username: [insert your user name]
  password:

